name: tgtg_client
description: >-
  Too Good To Go is a service that connects customers
  to restaurants and stores that have surplus unsold food.
  This is an unofficial client to access their API.
version: 0.0.3
environment:
  sdk: ">=2.18.2 <3.0.0"

repository: https://github.com/Azzeccagarbugli/tgtg_client
issue_tracker: https://github.com/Azzeccagarbugli/tgtg_client/issues
homepage: https://francescocoppola.me

dependencies:
  freezed_annotation: ^2.1.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.5.0
  lint: ^1.10.0
  test: ^1.16.0
